config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users
  resources :users, only: [:show]

  resources :shelves do
    resources :bookmarks, except: [:index]
  end

  resources :bookmarks do
    resources :likes, only: [:index, :create, :destroy]
  end

  get 'incoming_controller/create'
  post :incoming, to: 'incoming#create'
  get 'welcome/index'
  get 'welcome/about'
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Jaldi|League+Script|Montserrat|Playfair+Display+SC|Quintessential" rel="stylesheet">
  <link rel="stylesheet" href="animate.min.css">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <body class="layer1 tpad50">
    <div>
      <div class=" afont ht10rem">Linkbrary</div>
      <div class="wid25per lmar3per headlineb ht10 pull-left posrel rpad25"></div>
      <div class="wid25per headlineb rmar3per ht10 pull-right posrel lpad25"></div>
    </div>
    <div class="dropdown-hover abs tmar15 lmar25">
      <button class="glyphicon glyphicon-menu-hamburger dropdown-toggle bfont" data-toggle="dropdown"></button>
      <ul class="dropdown-menu cfont divider lmar10 font2rem">
        <li role="presentation">
          <%= link_to "Home", welcome_index_path, class: "tcent cfont" %>
        </li>
        <li role="presentation">
          <%= link_to "About", welcome_about_path, class: "tcent cfont" %>
        </li>
        <li role="presentation">
          <%= link_to "Shelves", shelves_path, class: "tcent cfont" %>
        </li>
        <% if user_signed_in? %>
          <li role="presentation">
            <%= link_to "Profile", user_path(current_user), class: "tcent cfont" %>
          </li>
          <li role="presentation">
            <%= link_to "Settings", edit_user_registration_path, class: "tcent cfont" %>
          </li>
        <% end %>
        <li role="presentation">
          <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "tcent cfont" %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: "tcent cfont"  %>
          <% end %>
        </li>
      </ul>
    </div>
  <%= yield %>
  </body>
</html>